/**
 * Key-terms flashcard content, one deck per career cluster (see
 * CLUSTER_SEED in seed-data.ts). Not pulled from a specific DECA PDF —
 * these are standard business-education vocabulary for each cluster,
 * the kind of term glossary a roleplay judge would expect a competitor
 * to already know cold.
 */
export const FLASHCARD_SEED: Record<string, { term: string; definition: string }[]> = {
  marketing: [
    { term: "Market Share", definition: "The percentage of total sales in a market captured by a particular business." },
    { term: "Market Segmentation", definition: "Dividing a broad market into subgroups of consumers with common needs or characteristics." },
    { term: "Target Market", definition: "The specific group of consumers a business aims its products and marketing efforts toward." },
    { term: "Marketing Mix (4 Ps)", definition: "The combination of product, price, place, and promotion a business uses to market its offering." },
    { term: "Brand Equity", definition: "The value a brand adds to a product beyond its functional benefits, based on consumer perception." },
    { term: "Product Life Cycle", definition: "The stages a product goes through: introduction, growth, maturity, and decline." },
    { term: "Elasticity of Demand", definition: "A measure of how much the quantity demanded of a good changes in response to a price change." },
    { term: "Positioning", definition: "The way a product is perceived by consumers relative to competing products." },
    { term: "Promotion Mix", definition: "The combination of advertising, personal selling, sales promotion, and public relations used to communicate with customers." },
    { term: "Channel of Distribution", definition: "The path a product takes from producer to final consumer." },
    { term: "Merchandising", definition: "Activities involved in promoting the sale of goods at retail." },
    { term: "Customer Relationship Management (CRM)", definition: "Strategies and tools businesses use to manage interactions with current and potential customers." },
    { term: "Value Proposition", definition: "The unique benefit a product or service offers that makes it attractive to customers." },
    { term: "Break-Even Point", definition: "The point at which total revenue equals total costs, resulting in neither profit nor loss." },
  ],
  finance: [
    { term: "Liquidity", definition: "How quickly an asset can be converted into cash without losing value." },
    { term: "Diversification", definition: "Spreading investments across different assets to reduce risk." },
    { term: "Interest Rate", definition: "The cost of borrowing money, expressed as a percentage of the loan amount." },
    { term: "Collateral", definition: "An asset pledged to a lender to secure a loan." },
    { term: "Compound Interest", definition: "Interest calculated on both the initial principal and accumulated interest from previous periods." },
    { term: "Cash Flow", definition: "The movement of money into and out of a business." },
    { term: "Equity", definition: "Ownership interest in a company, calculated as assets minus liabilities." },
    { term: "Balance Sheet", definition: "A financial statement showing a company's assets, liabilities, and equity at a point in time." },
    { term: "Net Income", definition: "A company's total earnings after subtracting all expenses from revenue." },
    { term: "Credit Score", definition: "A numerical rating of a person's creditworthiness based on their credit history." },
    { term: "Amortization", definition: "The gradual repayment of a loan through scheduled payments of principal and interest." },
    { term: "Risk Management", definition: "The process of identifying and mitigating potential financial losses." },
    { term: "Securities", definition: "Tradable financial instruments such as stocks and bonds that represent ownership or debt." },
    { term: "Portfolio", definition: "A collection of financial investments held by an individual or institution." },
  ],
  "business-management-administration": [
    { term: "Organizational Chart", definition: "A diagram showing the structure of a company and reporting relationships." },
    { term: "Delegation", definition: "Assigning responsibility and authority for a task to another person." },
    { term: "Human Resources Management", definition: "The function of recruiting, training, and managing employees." },
    { term: "Strategic Planning", definition: "The process of defining a company's long-term goals and how to achieve them." },
    { term: "Operations Management", definition: "Overseeing the processes that produce and deliver a company's goods or services." },
    { term: "SWOT Analysis", definition: "A planning tool that examines a business's Strengths, Weaknesses, Opportunities, and Threats." },
    { term: "Span of Control", definition: "The number of employees a manager directly supervises." },
    { term: "Business Ethics", definition: "Principles guiding acceptable conduct in business decision-making." },
    { term: "Productivity", definition: "A measure of output produced per unit of input." },
    { term: "Quality Control", definition: "Processes used to ensure products or services meet established standards." },
    { term: "Employee Empowerment", definition: "Giving employees authority and confidence to make decisions in their work." },
    { term: "Change Management", definition: "Structured approaches for transitioning individuals and organizations through change." },
    { term: "Knowledge Management", definition: "Processes for capturing, organizing, and sharing information within an organization." },
    { term: "Corporate Culture", definition: "The shared values, beliefs, and practices that characterize an organization." },
  ],
  entrepreneurship: [
    { term: "Venture Capital", definition: "Funding provided by investors to startups with high growth potential in exchange for equity." },
    { term: "Business Plan", definition: "A written document describing a business's goals, strategies, and financial projections." },
    { term: "Market Opportunity", definition: "A gap in the market that a business can fill with a new product or service." },
    { term: "Bootstrapping", definition: "Starting and growing a business using personal finances with minimal outside capital." },
    { term: "Scalability", definition: "A business's ability to grow revenue without a proportional increase in costs." },
    { term: "Angel Investor", definition: "A wealthy individual who provides capital for startups, often in exchange for ownership equity." },
    { term: "Pitch Deck", definition: "A brief presentation used to give investors a quick overview of a business plan." },
    { term: "Franchise", definition: "A license allowing an individual to operate a business using an established company's brand and system." },
    { term: "Intellectual Property", definition: "Legal rights protecting creations of the mind, such as patents, trademarks, and copyrights." },
    { term: "Minimum Viable Product (MVP)", definition: "A basic version of a product with just enough features to test it with early customers." },
    { term: "Exit Strategy", definition: "A plan for how an entrepreneur will eventually leave or sell their business." },
    { term: "Sole Proprietorship", definition: "A business owned and operated by one person with no legal distinction from the owner." },
    { term: "Risk Tolerance", definition: "The degree of variability in outcomes an entrepreneur is willing to accept." },
    { term: "Disruptive Innovation", definition: "A new product or service that significantly changes how an industry operates." },
  ],
  "hospitality-tourism": [
    { term: "Occupancy Rate", definition: "The percentage of available rooms or seats that are occupied over a given period." },
    { term: "Reservation System", definition: "Software or a process used to book and manage guest reservations." },
    { term: "Guest Experience", definition: "The overall perception and satisfaction a customer has during a hospitality interaction." },
    { term: "Yield Management", definition: "Adjusting prices based on demand to maximize revenue from a fixed number of rooms or seats." },
    { term: "Concierge Service", definition: "Personalized assistance provided to guests, such as recommendations and reservations." },
    { term: "Destination Marketing", definition: "Promoting a location to attract tourists and visitors." },
    { term: "Front of House", definition: "Areas and staff in a hospitality business that interact directly with guests." },
    { term: "Back of House", definition: "Areas and staff that support operations but don't interact directly with guests, such as kitchens." },
    { term: "Amenities", definition: "Features or services offered to guests to enhance their stay, such as pools or Wi-Fi." },
    { term: "Seasonality", definition: "Fluctuations in demand for travel and hospitality services based on time of year." },
    { term: "ADR (Average Daily Rate)", definition: "The average revenue earned per occupied room per day." },
    { term: "Loyalty Program", definition: "A rewards system designed to encourage repeat business from customers." },
    { term: "Sustainable Tourism", definition: "Travel and tourism practices that minimize negative environmental and cultural impact." },
    { term: "Event Planning", definition: "The process of organizing and coordinating logistics for gatherings or functions." },
  ],
  "personal-financial-literacy": [
    { term: "Budget", definition: "A plan for managing income and expenses over a period of time." },
    { term: "Net Worth", definition: "The value of everything a person owns minus everything they owe." },
    { term: "Gross Income", definition: "Total earnings before taxes and other deductions." },
    { term: "Net Income", definition: "Take-home pay remaining after taxes and deductions are subtracted from gross income." },
    { term: "Emergency Fund", definition: "Savings set aside to cover unexpected expenses." },
    { term: "Credit", definition: "The ability to borrow money or access goods and services with the understanding of paying later." },
    { term: "Debt-to-Income Ratio", definition: "A comparison of monthly debt payments to monthly gross income." },
    { term: "Compound Interest", definition: "Interest earned on both the initial deposit and previously earned interest." },
    { term: "Insurance Premium", definition: "The amount paid periodically for an insurance policy." },
    { term: "Tax Deduction", definition: "An expense that can be subtracted from taxable income, lowering the amount of tax owed." },
    { term: "Opportunity Cost", definition: "The value of the next best alternative given up when making a choice." },
    { term: "Identity Theft", definition: "The fraudulent use of someone's personal information, usually for financial gain." },
    { term: "Retirement Account", definition: "A savings account designed to provide income after a person stops working." },
    { term: "Inflation", definition: "The general increase in prices and decrease in purchasing power over time." },
  ],
};
