/**
 * Key-terms flashcard content, one deck per career cluster (see
 * CLUSTER_SEED in seed-data.ts).
 *
 * marketing, business-management-administration, entrepreneurship, and
 * hospitality-tourism are grounded in the actual uploaded exam banks: terms
 * were selected by frequency-analyzing every active question's stem,
 * options, and explanation for that cluster (see the session notes for the
 * n-gram extraction method), then cross-checked against standard DECA
 * cluster vocabulary and given accurate glossary-style definitions — not
 * copied verbatim from any question, since exam text is Q&A, not a
 * glossary. finance and personal-financial-literacy have no active exam
 * questions uploaded yet, so those two decks are intentionally left at
 * their original smaller, non-exam-derived set rather than expanded from
 * nothing.
 */
export const FLASHCARD_SEED: Record<string, { term: string; definition: string }[]> = {
  marketing: [
    { term: "Market Share", definition: "The percentage of total sales in a market captured by a particular business." },
    { term: "Market Segmentation", definition: "Dividing a broad market into subgroups of consumers with common needs or characteristics." },
    { term: "Target Market", definition: "The specific group of consumers a business aims its products and marketing efforts toward." },
    { term: "Marketing Mix (4 Ps)", definition: "The combination of product, price, place, and promotion a business uses to market its offering." },
    { term: "Brand Equity", definition: "The value a brand adds to a product beyond its functional benefits, based on consumer perception." },
    { term: "Product Life Cycle", definition: "The stages a product goes through: introduction, growth, maturity, and decline." },
    { term: "Elasticity of Demand", definition: "A measure of how much the quantity demanded of a good changes in response to a price change." },
    { term: "Positioning", definition: "The way a product is perceived by consumers relative to competing products." },
    { term: "Promotion Mix", definition: "The combination of advertising, personal selling, sales promotion, and public relations used to communicate with customers." },
    { term: "Channel of Distribution", definition: "The path a product takes from producer to final consumer." },
    { term: "Merchandising", definition: "Activities involved in promoting the sale of goods at retail." },
    { term: "Customer Relationship Management (CRM)", definition: "Strategies and tools businesses use to manage interactions with current and potential customers." },
    { term: "Value Proposition", definition: "The unique benefit a product or service offers that makes it attractive to customers." },
    { term: "Break-Even Point", definition: "The point at which total revenue equals total costs, resulting in neither profit nor loss." },
    { term: "Marketing Research", definition: "The systematic gathering, recording, and analysis of data about problems relating to marketing goods and services." },
    { term: "Primary Research", definition: "Data collected firsthand for a specific research purpose, such as a survey or focus group a company conducts itself." },
    { term: "Secondary Research", definition: "Data that already exists, originally collected for another purpose, such as government reports or trade publications." },
    { term: "Exploratory Research", definition: "Preliminary research used to clarify the nature of a problem, often through open-ended, unstructured methods." },
    { term: "Descriptive Research", definition: "Research designed to describe characteristics of a population or phenomenon, such as who buys a product and how often." },
    { term: "Causal Research", definition: "Research designed to determine cause-and-effect relationships between variables, such as how a price change affects sales." },
    { term: "Focus Group", definition: "A small group of people interviewed together to gather in-depth opinions about a product, service, or idea." },
    { term: "Survey Research", definition: "A research method that gathers information by asking a sample of people a standardized set of questions." },
    { term: "Observation Research", definition: "A research method that gathers data by watching how people actually behave, without direct interaction." },
    { term: "Random Sampling", definition: "A sampling method in which every member of the population has an equal chance of being selected." },
    { term: "Systematic Random Sampling", definition: "Selecting every nth person or item from a population list after a random starting point." },
    { term: "Stratified Sampling", definition: "Dividing a population into subgroups (strata) and sampling from each to ensure representation." },
    { term: "Convenience Sampling", definition: "Selecting survey respondents based on their easy availability rather than random selection." },
    { term: "Response Rate", definition: "The percentage of people in a sample who actually complete and return a survey." },
    { term: "Marketing Information System (MkIS)", definition: "The people, equipment, and procedures used to gather, sort, analyze, and distribute marketing information." },
    { term: "Situation Analysis", definition: "A review of a business's internal capabilities and external environment before making marketing decisions." },
    { term: "SWOT Analysis", definition: "A planning tool that examines a business's Strengths, Weaknesses, Opportunities, and Threats." },
    { term: "Marketing Plan", definition: "A written document detailing a business's marketing goals, strategies, and the actions needed to achieve them." },
    { term: "Environmental Scan", definition: "Monitoring the external environment — economic, social, technological, legal — for factors that affect marketing decisions." },
    { term: "Demographic Segmentation", definition: "Dividing a market based on measurable traits like age, gender, income, or education." },
    { term: "Geographic Segmentation", definition: "Dividing a market based on where consumers live, such as region, climate, or population density." },
    { term: "Psychographic Segmentation", definition: "Dividing a market based on lifestyle, values, attitudes, and personality traits." },
    { term: "Behavioral Segmentation", definition: "Dividing a market based on consumer behavior, such as usage rate, brand loyalty, or purchase occasion." },
    { term: "Mass Marketing", definition: "Marketing a product to the entire market with one basic strategy, without segmentation." },
    { term: "Niche Marketing", definition: "Targeting a narrow, specific segment of a market with tailored products or messaging." },
    { term: "Product Mix", definition: "The complete set of products a business offers for sale." },
    { term: "Product Line", definition: "A group of closely related products marketed by the same business under one brand." },
    { term: "Branding", definition: "The process of creating a distinct identity and image for a product in the minds of consumers." },
    { term: "Brand Loyalty", definition: "A consumer's consistent preference for and repeat purchase of a particular brand over competitors." },
    { term: "Brand Awareness", definition: "The extent to which consumers recognize or recall a particular brand." },
    { term: "Brand Image", definition: "The overall impression and associations consumers have with a brand." },
    { term: "Corporate Brand", definition: "The overall reputation and identity of a company itself, distinct from any single product it sells." },
    { term: "Packaging", definition: "The design and production of a container or wrapper for a product, which also serves marketing purposes." },
    { term: "Test Marketing", definition: "Introducing a new product in a limited market to gauge consumer reaction before a full launch." },
    { term: "Channel Members", definition: "The businesses and individuals — producers, wholesalers, retailers — involved in moving a product to the consumer." },
    { term: "Wholesaler", definition: "A business that buys goods in bulk from producers and resells them to retailers or other businesses." },
    { term: "Retailer", definition: "A business that sells goods or services directly to the final consumer." },
    { term: "Agent/Broker", definition: "A channel intermediary who negotiates sales or purchases without taking ownership of the goods." },
    { term: "Direct Channel", definition: "A distribution path in which a producer sells directly to the final consumer with no intermediaries." },
    { term: "Indirect Channel", definition: "A distribution path that uses one or more intermediaries between the producer and the final consumer." },
    { term: "Intensive Distribution", definition: "A strategy of selling a product through as many outlets as possible to maximize market coverage." },
    { term: "Selective Distribution", definition: "A strategy of selling a product through a limited number of carefully chosen outlets." },
    { term: "Exclusive Distribution", definition: "A strategy of selling a product through only one or a very few outlets in a given area." },
    { term: "Supply Chain Management", definition: "Coordinating the flow of goods, information, and finances from raw materials to the final customer." },
    { term: "Distribution Channel", definition: "The set of intermediaries a product passes through on its way from producer to consumer." },
    { term: "Inventory Control", definition: "Managing stock levels to balance product availability against the cost of holding inventory." },
    { term: "Channel Conflict", definition: "Disagreement among channel members over goals, roles, or rewards within a distribution channel." },
    { term: "Vertical Conflict", definition: "Conflict between different levels of the same distribution channel, such as a producer and a retailer." },
    { term: "Horizontal Conflict", definition: "Conflict between businesses at the same level of a distribution channel, such as two competing retailers." },
    { term: "Pricing Objectives", definition: "The goals a business sets for its pricing strategy, such as maximizing profit, sales volume, or market share." },
    { term: "Markup", definition: "The amount added to a product's cost to determine its selling price." },
    { term: "Markdown", definition: "A reduction from a product's original selling price." },
    { term: "Price Skimming", definition: "Setting a high initial price for a new product and lowering it over time as competition increases." },
    { term: "Penetration Pricing", definition: "Setting a low initial price for a new product to quickly attract customers and gain market share." },
    { term: "Psychological Pricing", definition: "Pricing strategies, such as $9.99 instead of $10, designed to make a price seem more appealing." },
    { term: "Predatory Pricing", definition: "Setting prices very low, often below cost, to drive competitors out of the market." },
    { term: "Personal Selling", definition: "Direct, one-on-one communication between a salesperson and a customer to make a sale." },
    { term: "Preapproach", definition: "The step in the sales process where a salesperson researches a prospect before making contact." },
    { term: "Approach (Selling)", definition: "The initial contact a salesperson makes with a customer to open a sales presentation." },
    { term: "Needs Assessment", definition: "Determining a customer's wants and needs before recommending a product or service." },
    { term: "Handling Objections", definition: "The step in personal selling where a salesperson addresses a customer's concerns or hesitations." },
    { term: "Closing the Sale", definition: "The step in personal selling where the salesperson secures the customer's commitment to purchase." },
    { term: "Follow-Up (Selling)", definition: "Contacting a customer after a sale to ensure satisfaction and encourage repeat business." },
    { term: "Suggestion Selling", definition: "Recommending additional or related products to a customer who has already decided to buy." },
    { term: "Substitute Selling", definition: "Recommending an alternative product when the one a customer wants is unavailable." },
    { term: "Feature-Benefit Selling", definition: "Explaining a product's characteristics (features) in terms of what they do for the customer (benefits)." },
    { term: "Prospecting", definition: "The process of identifying potential customers for a product or service." },
    { term: "Rapport", definition: "A friendly, trusting relationship a salesperson builds with a customer." },
    { term: "Order Taking", definition: "Processing a routine sale for a customer who has already decided to purchase." },
    { term: "Order Getting", definition: "Actively seeking out and persuading customers to purchase, often through creative selling." },
    { term: "Buying Motives", definition: "The reasons, needs, or emotions that drive a consumer to make a purchase." },
    { term: "Rational Buying Motives", definition: "Purchase reasons based on logical factors like price, durability, or convenience." },
    { term: "Emotional Buying Motives", definition: "Purchase reasons based on feelings, such as status, fear, or desire for approval." },
    { term: "Public Relations", definition: "Nonpaid, nonpersonal communication used to build goodwill between a business and the public." },
    { term: "Publicity", definition: "Free media coverage of a business or product, not directly paid for by the company." },
    { term: "Press Release", definition: "A written statement distributed to the media to announce news about a business or product." },
    { term: "Sales Promotion", definition: "Short-term incentives, such as coupons or contests, used to encourage immediate purchase." },
    { term: "Coupon", definition: "A sales promotion offering a discount on a specific product, typically redeemed at purchase." },
    { term: "Rebate", definition: "A partial refund given to a customer after they purchase a product, usually requiring proof of purchase." },
    { term: "Premium (Sales Promotion)", definition: "A free or low-cost item given to a customer as an incentive to purchase a product." },
    { term: "Word-of-Mouth Marketing", definition: "The spread of product information from person to person through informal conversation." },
    { term: "Viral Marketing", definition: "A marketing strategy that encourages people to share a message online, spreading it rapidly like a virus." },
    { term: "Social Media Marketing", definition: "Using social media platforms to promote a product, brand, or service and engage with customers." },
    { term: "Search Engine Optimization (SEO)", definition: "Improving a website so it ranks higher in search engine results, increasing organic traffic." },
    { term: "Direct Marketing", definition: "Marketing that communicates directly with targeted individual consumers to generate a response." },
    { term: "Marketing Ethics", definition: "Standards of right and wrong conduct that apply to marketing decisions and practices." },
    { term: "The Seven Marketing Functions", definition: "Distribution, financing, marketing-information management, pricing, product/service management, promotion, and selling." },
    { term: "Channel Management (Marketing Function)", definition: "The marketing function of selecting and overseeing the intermediaries used to distribute a product." },
    { term: "Nonpersonal Selling", definition: "Promotion, such as advertising, that reaches a mass audience without direct interpersonal contact." },
  ],
  finance: [
    { term: "Liquidity", definition: "How quickly an asset can be converted into cash without losing value." },
    { term: "Diversification", definition: "Spreading investments across different assets to reduce risk." },
    { term: "Interest Rate", definition: "The cost of borrowing money, expressed as a percentage of the loan amount." },
    { term: "Collateral", definition: "An asset pledged to a lender to secure a loan." },
    { term: "Compound Interest", definition: "Interest calculated on both the initial principal and accumulated interest from previous periods." },
    { term: "Cash Flow", definition: "The movement of money into and out of a business." },
    { term: "Equity", definition: "Ownership interest in a company, calculated as assets minus liabilities." },
    { term: "Balance Sheet", definition: "A financial statement showing a company's assets, liabilities, and equity at a point in time." },
    { term: "Net Income", definition: "A company's total earnings after subtracting all expenses from revenue." },
    { term: "Credit Score", definition: "A numerical rating of a person's creditworthiness based on their credit history." },
    { term: "Amortization", definition: "The gradual repayment of a loan through scheduled payments of principal and interest." },
    { term: "Risk Management", definition: "The process of identifying and mitigating potential financial losses." },
    { term: "Securities", definition: "Tradable financial instruments such as stocks and bonds that represent ownership or debt." },
    { term: "Portfolio", definition: "A collection of financial investments held by an individual or institution." },
  ],
  "business-management-administration": [
    { term: "Organizational Chart", definition: "A diagram showing the structure of a company and reporting relationships." },
    { term: "Delegation", definition: "Assigning responsibility and authority for a task to another person." },
    { term: "Human Resources Management", definition: "The function of recruiting, training, and managing employees." },
    { term: "Strategic Planning", definition: "The process of defining a company's long-term goals and how to achieve them." },
    { term: "Operations Management", definition: "Overseeing the processes that produce and deliver a company's goods or services." },
    { term: "SWOT Analysis", definition: "A planning tool that examines a business's Strengths, Weaknesses, Opportunities, and Threats." },
    { term: "Span of Control", definition: "The number of employees a manager directly supervises." },
    { term: "Business Ethics", definition: "Principles guiding acceptable conduct in business decision-making." },
    { term: "Productivity", definition: "A measure of output produced per unit of input." },
    { term: "Quality Control", definition: "Processes used to ensure products or services meet established standards." },
    { term: "Employee Empowerment", definition: "Giving employees authority and confidence to make decisions in their work." },
    { term: "Change Management", definition: "Structured approaches for transitioning individuals and organizations through change." },
    { term: "Knowledge Management", definition: "Processes for capturing, organizing, and sharing information within an organization." },
    { term: "Corporate Culture", definition: "The shared values, beliefs, and practices that characterize an organization." },
    { term: "Supply Chain Management", definition: "Coordinating the flow of goods, information, and finances from suppliers through to the customer." },
    { term: "Line Organization", definition: "A simple organizational structure with a direct chain of command from top management down." },
    { term: "Line-and-Staff Organization", definition: "A structure combining direct-authority line positions with advisory staff positions that support them." },
    { term: "Matrix Organization", definition: "A structure where employees report to both a functional manager and a project manager." },
    { term: "Chain of Command", definition: "The formal line of authority through which orders and communication flow in an organization." },
    { term: "Centralization", definition: "Concentrating decision-making authority at the top levels of an organization." },
    { term: "Decentralization", definition: "Distributing decision-making authority to lower levels throughout an organization." },
    { term: "Departmentalization", definition: "Grouping jobs and employees into units based on function, product, geography, or customer." },
    { term: "Job Analysis", definition: "The process of studying a job to determine its duties, responsibilities, and requirements." },
    { term: "Job Description", definition: "A written statement outlining the duties, responsibilities, and requirements of a specific position." },
    { term: "Recruitment", definition: "The process of attracting qualified candidates to apply for job openings." },
    { term: "Onboarding", definition: "The process of integrating a new employee into an organization and its culture." },
    { term: "Performance Appraisal", definition: "A formal evaluation of an employee's job performance, typically conducted periodically." },
    { term: "Compensation", definition: "The total pay and benefits an employee receives in exchange for their work." },
    { term: "Employee Benefits", definition: "Non-wage compensation provided to employees, such as health insurance or retirement plans." },
    { term: "Collective Bargaining", definition: "The negotiation process between an employer and a labor union over wages and working conditions." },
    { term: "Labor Union", definition: "An organization of workers formed to negotiate collectively with employers on their behalf." },
    { term: "Workplace Safety", definition: "Policies and practices designed to prevent injury and protect employee health on the job." },
    { term: "OSHA", definition: "The Occupational Safety and Health Administration, a federal agency that regulates workplace safety." },
    { term: "Ergonomics", definition: "The study of designing equipment and workspaces to fit the people who use them, reducing strain and injury." },
    { term: "Work Breakdown Structure", definition: "A hierarchical breakdown of a project into smaller, manageable tasks." },
    { term: "Project Management", definition: "Planning, organizing, and overseeing resources to complete a specific project on time and within budget." },
    { term: "Six Sigma", definition: "A data-driven methodology for eliminating defects and improving process quality." },
    { term: "Continuous Improvement", definition: "An ongoing effort to incrementally improve products, services, or processes over time." },
    { term: "Total Quality Management (TQM)", definition: "A management approach focused on continuous improvement and quality across every part of an organization." },
    { term: "Benchmarking", definition: "Comparing a company's processes and performance metrics to industry bests or competitors." },
    { term: "Key Performance Indicator (KPI)", definition: "A measurable value used to evaluate how effectively an organization is achieving its objectives." },
    { term: "Business Plan", definition: "A written document describing a company's goals, strategies, and financial projections." },
    { term: "Mission Statement", definition: "A brief statement defining an organization's core purpose and reason for existing." },
    { term: "Vision Statement", definition: "A statement describing what an organization aspires to become in the future." },
    { term: "Stakeholder", definition: "Any person or group with an interest in or affected by a business's decisions and operations." },
    { term: "Shareholder", definition: "An individual or entity that owns shares of stock in a corporation." },
    { term: "Board of Directors", definition: "A group elected by shareholders to oversee a corporation's management and major decisions." },
    { term: "Corporate Governance", definition: "The system of rules and practices by which a company is directed and controlled." },
    { term: "Sole Proprietorship", definition: "A business owned and operated by one person, with no legal separation between owner and business." },
    { term: "Partnership", definition: "A business owned by two or more people who share profits, losses, and management responsibilities." },
    { term: "Corporation", definition: "A business that is legally separate from its owners, who hold ownership through shares of stock." },
    { term: "Limited Liability Company (LLC)", definition: "A business structure combining the liability protection of a corporation with the tax benefits of a partnership." },
    { term: "Nonprofit Organization", definition: "An organization operated for a charitable, educational, or social purpose rather than to generate profit for owners." },
    { term: "Outsourcing", definition: "Contracting a business function or process to an outside company instead of performing it in-house." },
    { term: "Succession Planning", definition: "Identifying and developing employees to fill key leadership positions in the future." },
    { term: "Talent Management", definition: "The ongoing process of attracting, developing, and retaining skilled employees." },
    { term: "Diversity and Inclusion", definition: "Practices aimed at ensuring representation and fair treatment of people from varied backgrounds in the workplace." },
    { term: "Telecommuting", definition: "Working remotely, outside a traditional office, using technology to communicate with the employer." },
    { term: "At-Will Employment", definition: "An employment arrangement in which either the employer or employee may end the relationship at any time." },
    { term: "Nondisclosure Agreement (NDA)", definition: "A legal contract preventing parties from sharing confidential information they've agreed to keep private." },
    { term: "Noncompete Clause", definition: "A contract provision restricting an employee from working for a competitor after leaving a company." },
    { term: "Trademark", definition: "A legally protected symbol, name, or design that identifies a company's goods or services." },
    { term: "Copyright", definition: "Legal protection granted to the creator of an original work, such as writing, music, or art." },
    { term: "Patent", definition: "A legal right granting an inventor exclusive control over the use and sale of an invention for a set period." },
    { term: "Trade Secret", definition: "Confidential business information that gives a company a competitive advantage and is protected from disclosure." },
    { term: "Fiduciary Duty", definition: "A legal obligation to act in the best financial interest of another party, such as shareholders." },
    { term: "Corporate Social Responsibility (CSR)", definition: "A business's commitment to operating in ways that benefit society and the environment, beyond profit alone." },
    { term: "Crisis Management", definition: "The process a business uses to prepare for and respond to unexpected, disruptive events." },
    { term: "Time Management", definition: "Planning and organizing how to divide time effectively between different tasks and priorities." },
    { term: "Motivation Theory", definition: "Frameworks that explain what drives employees to perform and stay engaged at work." },
    { term: "Maslow's Hierarchy of Needs", definition: "A motivation theory ranking human needs from basic (physiological, safety) to higher-level (esteem, self-actualization)." },
    { term: "Herzberg's Two-Factor Theory", definition: "A motivation theory distinguishing hygiene factors, which prevent dissatisfaction, from motivators, which drive satisfaction." },
    { term: "Theory X and Theory Y", definition: "Two contrasting management assumptions about employees — that they dislike work and must be controlled (X), or are self-motivated (Y)." },
    { term: "Leadership Style", definition: "The general approach and behavior a manager uses to direct, motivate, and interact with employees." },
    { term: "Autocratic Leadership", definition: "A leadership style where the manager makes decisions unilaterally with little employee input." },
    { term: "Democratic Leadership", definition: "A leadership style where the manager involves employees in the decision-making process." },
    { term: "Laissez-Faire Leadership", definition: "A hands-off leadership style where employees are given significant freedom to make their own decisions." },
    { term: "Team Building", definition: "Activities and strategies designed to improve cooperation and performance among a group of employees." },
    { term: "Conflict Resolution", definition: "Methods and processes used to peacefully resolve disagreements between individuals or groups." },
    { term: "Negotiation", definition: "A discussion between parties aimed at reaching a mutually acceptable agreement." },
    { term: "Code of Conduct", definition: "A set of rules outlining the expected behavior and ethical standards for employees of an organization." },
    { term: "Whistleblower", definition: "An employee who reports illegal or unethical conduct occurring within their organization." },
    { term: "Due Diligence", definition: "A thorough investigation and evaluation of a business or investment before entering into an agreement." },
    { term: "Liability", definition: "A legal or financial obligation a business owes to another party." },
    { term: "Negligence", definition: "A failure to exercise reasonable care, resulting in harm or damage to another party." },
    { term: "Income Statement", definition: "A financial statement showing a company's revenues, expenses, and profit over a period of time." },
    { term: "Net Income", definition: "A company's total earnings after subtracting all expenses from revenue." },
    { term: "Operating Expenses", definition: "The costs a business incurs through its normal day-to-day operations, such as rent and utilities." },
    { term: "Accounts Receivable", definition: "Money owed to a business by customers who have purchased goods or services on credit." },
    { term: "Accounts Payable", definition: "Money a business owes to its suppliers or creditors for goods or services received." },
    { term: "Break-Even Analysis", definition: "A calculation to determine the sales volume needed for revenue to equal total costs." },
    { term: "Return on Investment (ROI)", definition: "A measure of the profitability of an investment, calculated as gain divided by cost." },
    { term: "Economies of Scale", definition: "Cost advantages a business gains as production increases, spreading fixed costs over more units." },
    { term: "Private Enterprise System", definition: "An economic system in which businesses are privately owned and operated for profit, with limited government control." },
    { term: "Creative Destruction", definition: "The process by which innovation continually replaces outdated products, processes, and businesses." },
    { term: "Work Ethic", definition: "A belief in the value of hard work and diligence, reflected in an employee's dedication and reliability." },
    { term: "Problem Solving", definition: "The process of identifying a challenge, analyzing options, and implementing a solution." },
    { term: "Call Center", definition: "A centralized department that handles a high volume of customer calls, whether inbound or outbound." },
    { term: "Installment Credit", definition: "A loan repaid in a series of scheduled, equal payments over time." },
    { term: "Debtor-Creditor Relationship", definition: "The legal relationship between a borrower (debtor) and a lender (creditor) involving an obligation to repay." },
    { term: "Credit Union", definition: "A member-owned financial cooperative that offers banking services, often at more favorable rates than traditional banks." },
    { term: "Cash From Operating Activities", definition: "The section of a cash flow statement showing cash generated or used by a company's core business operations." },
    { term: "Persuasion", definition: "The act of convincing others to adopt a particular viewpoint or take a specific action, a key workplace communication skill." },
    { term: "Organizational Behavior", definition: "The study of how individuals and groups behave within an organization and how that behavior affects performance." },
    { term: "Employee Turnover", definition: "The rate at which employees leave a company and are replaced by new hires." },
    { term: "Absenteeism", definition: "The habitual failure of an employee to report to work as scheduled." },
    { term: "Grievance Procedure", definition: "A formal process that allows employees to raise and resolve workplace complaints." },
    { term: "Arbitration", definition: "A method of resolving disputes in which a neutral third party reviews the case and makes a binding decision." },
    { term: "Mediation", definition: "A method of resolving disputes in which a neutral third party helps the parties reach a voluntary agreement." },
  ],
  entrepreneurship: [
    { term: "Venture Capital", definition: "Funding provided by investors to startups with high growth potential in exchange for equity." },
    { term: "Business Plan", definition: "A written document describing a business's goals, strategies, and financial projections." },
    { term: "Market Opportunity", definition: "A gap in the market that a business can fill with a new product or service." },
    { term: "Bootstrapping", definition: "Starting and growing a business using personal finances with minimal outside capital." },
    { term: "Scalability", definition: "A business's ability to grow revenue without a proportional increase in costs." },
    { term: "Angel Investor", definition: "A wealthy individual who provides capital for startups, often in exchange for ownership equity." },
    { term: "Pitch Deck", definition: "A brief presentation used to give investors a quick overview of a business plan." },
    { term: "Franchise", definition: "A license allowing an individual to operate a business using an established company's brand and system." },
    { term: "Intellectual Property", definition: "Legal rights protecting creations of the mind, such as patents, trademarks, and copyrights." },
    { term: "Minimum Viable Product (MVP)", definition: "A basic version of a product with just enough features to test it with early customers." },
    { term: "Exit Strategy", definition: "A plan for how an entrepreneur will eventually leave or sell their business." },
    { term: "Sole Proprietorship", definition: "A business owned and operated by one person with no legal distinction from the owner." },
    { term: "Risk Tolerance", definition: "The degree of variability in outcomes an entrepreneur is willing to accept." },
    { term: "Disruptive Innovation", definition: "A new product or service that significantly changes how an industry operates." },
    { term: "Competitive Advantage", definition: "A distinct edge that allows a business to outperform its competitors, such as lower costs or unique features." },
    { term: "Managerial Accounting", definition: "Accounting focused on providing information to internal managers for planning and decision-making." },
    { term: "Corporate Governance", definition: "The system of rules and practices by which a company is directed and controlled." },
    { term: "Risk Assessment", definition: "The process of identifying and evaluating potential risks a venture may face." },
    { term: "Cash Flow", definition: "The movement of money into and out of a business over a period of time." },
    { term: "Mission Statement", definition: "A brief statement defining a business's core purpose and reason for existing." },
    { term: "Vertical Analysis", definition: "A financial statement analysis method expressing each line item as a percentage of a base figure, like total assets." },
    { term: "Owner's Equity", definition: "The owner's claim on business assets, calculated as total assets minus total liabilities." },
    { term: "Sales Forecast", definition: "A projection of future sales based on historical data, market trends, and other factors." },
    { term: "Net Profit", definition: "The amount of revenue remaining after all business expenses, taxes, and costs have been deducted." },
    { term: "Financial Statements", definition: "Formal records — including the income statement, balance sheet, and cash flow statement — that report a business's financial activities." },
    { term: "Payroll Taxes", definition: "Taxes withheld from employee wages and paid by employers to fund programs like Social Security and Medicare." },
    { term: "Income Statement", definition: "A financial statement showing a company's revenues, expenses, and profit over a period of time." },
    { term: "Consumer Behavior", definition: "The study of how individuals make decisions to purchase, use, and dispose of goods and services." },
    { term: "Marketing Mix", definition: "The combination of product, price, place, and promotion a business uses to market its offering." },
    { term: "Pricing Objectives", definition: "The goals a business sets for its pricing strategy, such as maximizing profit, sales volume, or market share." },
    { term: "Email Marketing", definition: "Sending targeted commercial messages directly to a group of people via email." },
    { term: "Search Engine Optimization (SEO)", definition: "Improving a website so it ranks higher in search engine results, increasing organic traffic." },
    { term: "Royalty", definition: "A payment made to the owner of intellectual property, such as a franchise or patent, for its use." },
    { term: "Entrepreneurial Discovery", definition: "The process by which an entrepreneur identifies an unmet need or overlooked opportunity in the market." },
    { term: "Variable Expenses", definition: "Costs that change in proportion to a business's level of production or sales." },
    { term: "Fixed Expenses", definition: "Costs that remain constant regardless of a business's level of production or sales." },
    { term: "Vendor Performance", definition: "A measure of how reliably and effectively a supplier meets a business's expectations for quality, cost, and delivery." },
    { term: "SWOT Analysis", definition: "A planning tool that examines a business's Strengths, Weaknesses, Opportunities, and Threats." },
    { term: "Word-of-Mouth Marketing", definition: "The spread of product information from person to person through informal conversation." },
    { term: "Financial Risk", definition: "The possibility of losing money on a business venture or investment." },
    { term: "Business Model", definition: "A company's plan for how it creates, delivers, and captures value, including how it generates revenue." },
    { term: "Value Proposition", definition: "The unique benefit a product or service offers that makes it attractive to customers." },
    { term: "Startup", definition: "A newly formed company, typically designed to grow quickly and scale a new product or business model." },
    { term: "Lean Startup", definition: "A method for developing a business by launching a minimum viable product and iterating based on customer feedback." },
    { term: "Pivot (Business)", definition: "A fundamental change in a startup's business strategy based on market feedback or new information." },
    { term: "Prototype", definition: "An early sample or model of a product built to test a concept before full-scale production." },
    { term: "Crowdfunding", definition: "Raising small amounts of capital from a large number of people, typically via an online platform." },
    { term: "Equity Financing", definition: "Raising capital by selling shares of ownership in a company." },
    { term: "Debt Financing", definition: "Raising capital by borrowing money that must be repaid with interest." },
    { term: "Line of Credit", definition: "A flexible loan from a financial institution that a business can draw on up to a set limit as needed." },
    { term: "Working Capital", definition: "The funds available for a business's day-to-day operations, calculated as current assets minus current liabilities." },
    { term: "Break-Even Point", definition: "The point at which total revenue equals total costs, resulting in neither profit nor loss." },
    { term: "Gross Profit Margin", definition: "The percentage of revenue remaining after subtracting the cost of goods sold." },
    { term: "Net Profit Margin", definition: "The percentage of revenue remaining as profit after all expenses have been deducted." },
    { term: "Return on Investment (ROI)", definition: "A measure of the profitability of an investment, calculated as gain divided by cost." },
    { term: "Elevator Pitch", definition: "A concise, persuasive summary of a business idea that can be delivered in the time of a short elevator ride." },
    { term: "Competitive Analysis", definition: "Evaluating competitors' strengths, weaknesses, and strategies to inform a business's own strategy." },
    { term: "Barriers to Entry", definition: "Obstacles, such as high startup costs or regulations, that make it difficult for new competitors to enter a market." },
    { term: "First-Mover Advantage", definition: "The competitive edge gained by being the first business to enter a market with a new product." },
    { term: "Licensing", definition: "An agreement allowing one party to use another's intellectual property in exchange for a fee or royalty." },
    { term: "Trademark", definition: "A legally protected symbol, name, or design that identifies a company's goods or services." },
    { term: "Patent", definition: "A legal right granting an inventor exclusive control over the use and sale of an invention for a set period." },
    { term: "Trade Secret", definition: "Confidential business information that gives a company a competitive advantage and is protected from disclosure." },
    { term: "Limited Liability", definition: "Legal protection that limits an owner's personal financial responsibility for a business's debts to their investment in it." },
    { term: "Partnership Agreement", definition: "A legal document outlining the terms, responsibilities, and profit-sharing arrangement between business partners." },
    { term: "Articles of Incorporation", definition: "The legal document filed with a state to formally establish a corporation." },
    { term: "Small Business Administration (SBA)", definition: "A U.S. government agency that supports small businesses through loans, counseling, and resources." },
    { term: "Accounts Receivable", definition: "Money owed to a business by customers who have purchased goods or services on credit." },
    { term: "Accounts Payable", definition: "Money a business owes to its suppliers or creditors for goods or services received." },
    { term: "Balance Sheet", definition: "A financial statement showing a company's assets, liabilities, and equity at a point in time." },
    { term: "Overhead Costs", definition: "Ongoing business expenses not directly tied to producing a specific product or service." },
    { term: "Economies of Scale", definition: "Cost advantages a business gains as production increases, spreading fixed costs over more units." },
    { term: "Market Penetration", definition: "A growth strategy focused on increasing sales of existing products in existing markets." },
    { term: "Product Development", definition: "A growth strategy focused on creating new products to sell to an existing market." },
    { term: "Market Development", definition: "A growth strategy focused on selling existing products to new markets." },
    { term: "Diversification (Growth Strategy)", definition: "A growth strategy involving new products in new markets, often the riskiest growth option." },
    { term: "Business Incubator", definition: "An organization that supports early-stage startups with resources like office space, mentorship, and funding access." },
    { term: "Feasibility Study", definition: "An analysis of whether a proposed business idea is practical and likely to succeed." },
    { term: "Target Market", definition: "The specific group of consumers a business aims its products and marketing efforts toward." },
    { term: "Unique Selling Proposition (USP)", definition: "The specific factor that differentiates a product from all its competitors." },
    { term: "Customer Acquisition Cost", definition: "The total cost of sales and marketing efforts required to gain one new customer." },
    { term: "Social Entrepreneurship", definition: "Starting a venture primarily to solve a social or environmental problem, rather than to maximize profit alone." },
    { term: "Intrapreneurship", definition: "Acting like an entrepreneur while working within a large, existing organization." },
    { term: "Total Addressable Market (TAM)", definition: "The total revenue opportunity available if a product or service achieved 100% market share." },
    { term: "Customer Lifetime Value (CLV)", definition: "The total revenue a business can expect from a single customer account over the course of their relationship." },
    { term: "Burn Rate", definition: "The rate at which a startup spends its available cash before generating positive cash flow." },
    { term: "Runway (Startup)", definition: "The amount of time a startup can continue operating before it runs out of cash." },
    { term: "Series A Funding", definition: "The first major round of venture capital financing a startup raises after its initial seed funding." },
    { term: "Seed Funding", definition: "The initial capital raised to start a business, often used to develop a product and validate the concept." },
    { term: "Sweat Equity", definition: "Ownership interest earned through labor and effort invested in a business rather than through cash investment." },
    { term: "Business Accelerator", definition: "A program that provides startups with mentorship, resources, and funding over a fixed, intensive period in exchange for equity." },
    { term: "Franchisee", definition: "An individual or business that purchases the right to operate a franchise using another company's brand and system." },
    { term: "Franchisor", definition: "The company that owns a brand and business system and grants others the right to operate franchises under it." },
    { term: "Product-Market Fit", definition: "The degree to which a product satisfies strong demand in its target market." },
    { term: "Customer Validation", definition: "The process of confirming that real customers want and will pay for a proposed product or service." },
    { term: "Go-to-Market Strategy", definition: "A plan detailing how a company will reach target customers and gain a competitive advantage when launching a product." },
    { term: "Networking (Business)", definition: "Building and maintaining professional relationships that can provide business opportunities and support." },
    { term: "Mentor (Entrepreneurship)", definition: "An experienced individual who provides guidance and advice to a less experienced entrepreneur." },
    { term: "Sustainability (Business)", definition: "Operating a business in a way that meets present needs without compromising future generations' ability to meet theirs." },
    { term: "Gross Domestic Product (GDP)", definition: "The total monetary value of all goods and services produced within a country over a given period." },
    { term: "Economic Indicator", definition: "A statistic, such as unemployment or GDP, used to gauge the current state and direction of the economy." },
    { term: "Opportunity Cost", definition: "The value of the next best alternative given up when making a choice." },
    { term: "Supply and Demand", definition: "The economic principle describing how the availability of a good and consumer desire for it interact to determine price." },
  ],
  "hospitality-tourism": [
    { term: "Occupancy Rate", definition: "The percentage of available rooms or seats that are occupied over a given period." },
    { term: "Reservation System", definition: "Software or a process used to book and manage guest reservations." },
    { term: "Guest Experience", definition: "The overall perception and satisfaction a customer has during a hospitality interaction." },
    { term: "Yield Management", definition: "Adjusting prices based on demand to maximize revenue from a fixed number of rooms or seats." },
    { term: "Concierge Service", definition: "Personalized assistance provided to guests, such as recommendations and reservations." },
    { term: "Destination Marketing", definition: "Promoting a location to attract tourists and visitors." },
    { term: "Front of House", definition: "Areas and staff in a hospitality business that interact directly with guests." },
    { term: "Back of House", definition: "Areas and staff that support operations but don't interact directly with guests, such as kitchens." },
    { term: "Amenities", definition: "Features or services offered to guests to enhance their stay, such as pools or Wi-Fi." },
    { term: "Seasonality", definition: "Fluctuations in demand for travel and hospitality services based on time of year." },
    { term: "ADR (Average Daily Rate)", definition: "The average revenue earned per occupied room per day." },
    { term: "Loyalty Program", definition: "A rewards system designed to encourage repeat business from customers." },
    { term: "Sustainable Tourism", definition: "Travel and tourism practices that minimize negative environmental and cultural impact." },
    { term: "Event Planning", definition: "The process of organizing and coordinating logistics for gatherings or functions." },
    { term: "Suggestion Selling", definition: "Recommending additional or related products to a guest who has already decided to buy." },
    { term: "Substitute Selling", definition: "Recommending an alternative product or service when the one a guest wants is unavailable." },
    { term: "Personal Selling", definition: "Direct, one-on-one communication between staff and a guest to make a sale." },
    { term: "Sales Promotion", definition: "Short-term incentives, such as discounts or packages, used to encourage immediate bookings or purchases." },
    { term: "Travel Agency", definition: "A business that arranges travel services, such as flights, hotels, and tours, on behalf of clients." },
    { term: "Travel Agent", definition: "A professional who plans and books travel arrangements for clients." },
    { term: "Tour Operator", definition: "A company that creates and sells package tours, combining transportation, lodging, and activities." },
    { term: "Buying Decision", definition: "The process and factors that lead a consumer to choose one product, service, or destination over another." },
    { term: "Petty Cash", definition: "A small amount of cash kept on hand for minor, incidental business expenses." },
    { term: "Amusement Park", definition: "A facility offering rides, games, and entertainment, typically for a fee or admission ticket." },
    { term: "Core Values", definition: "The fundamental beliefs and principles that guide an organization's culture and decision-making." },
    { term: "Channel Members", definition: "The businesses involved in bringing a travel or hospitality product to the final customer, such as agents and tour operators." },
    { term: "Marketing Research", definition: "The systematic gathering, recording, and analysis of data about problems relating to marketing goods and services." },
    { term: "Special Event", definition: "A one-time or infrequent occasion, such as a festival or conference, planned to achieve specific goals." },
    { term: "Local Community", definition: "The residents and organizations in the area surrounding a hospitality or tourism business, often a key stakeholder group." },
    { term: "Professional Organization", definition: "An association that supports and represents members of a specific industry or profession." },
    { term: "Trade Show", definition: "An event where businesses in an industry showcase products and services to other businesses and potential partners." },
    { term: "Nonpersonal Presentation", definition: "Promotion, such as advertising, that reaches an audience without direct interpersonal contact." },
    { term: "Publicity", definition: "Free media coverage of a business, destination, or event, not directly paid for by the company." },
    { term: "Hotel Chain", definition: "A group of hotels operating under the same brand, often with shared standards and a central reservation system." },
    { term: "Distribution Channel", definition: "The path through which a travel or hospitality product reaches the final consumer." },
    { term: "Competitive Advantage", definition: "A distinct edge that allows a business to outperform its competitors, such as location or service quality." },
    { term: "Human Resources", definition: "The department responsible for recruiting, training, and managing an organization's employees." },
    { term: "Financial Planner", definition: "A professional who helps individuals or businesses manage budgets, investments, and financial goals." },
    { term: "Public Relations", definition: "Nonpaid, nonpersonal communication used to build goodwill between a business and the public." },
    { term: "Print Advertisement", definition: "A paid promotional message published in newspapers, magazines, or other printed materials." },
    { term: "Channel Management", definition: "Selecting and overseeing the intermediaries, such as agents and online platforms, used to distribute a hospitality product." },
    { term: "Gift Shop", definition: "A retail outlet within a hotel, attraction, or tourism venue that sells souvenirs and sundries to guests." },
    { term: "Planned Personalized Communication", definition: "Deliberate, tailored messaging aimed at building a specific relationship with a customer or client." },
    { term: "Guest Rooms", definition: "The sleeping accommodations offered to guests at a lodging property." },
    { term: "Sales Representative", definition: "An employee responsible for selling a hospitality business's services, often to corporate or group clients." },
    { term: "Written Communication", definition: "Conveying information through text, such as emails, letters, or reports, rather than speech." },
    { term: "Oral Presentation", definition: "Delivering information or a message to an audience through spoken communication." },
    { term: "American Marketing Association", definition: "A professional association for marketing professionals that sets standards and provides resources for the field." },
    { term: "Purchasing Agent", definition: "An employee responsible for buying goods and supplies needed by a business." },
    { term: "Search Engine Optimization (SEO)", definition: "Improving a website so it ranks higher in search engine results, increasing organic traffic." },
    { term: "Viral Marketing", definition: "A marketing strategy that encourages people to share a message online, spreading it rapidly like a virus." },
    { term: "Press Kit", definition: "A package of promotional materials, such as photos and fact sheets, provided to media to support a publicity effort." },
    { term: "Word-of-Mouth Marketing", definition: "The spread of product or destination information from person to person through informal conversation." },
    { term: "Corporate Blog", definition: "An online publication maintained by a business to share news, expertise, and promotional content." },
    { term: "Quality Assurance", definition: "Processes used to ensure a hospitality business's services consistently meet established standards." },
    { term: "Executive Summary", definition: "A brief overview at the beginning of a report or business plan summarizing its key points." },
    { term: "Research Findings", definition: "The conclusions and data gathered from a research study, used to inform business decisions." },
    { term: "Tax Return", definition: "A form filed with a government agency reporting income and calculating taxes owed." },
    { term: "Global Positioning System (GPS)", definition: "A satellite-based navigation system used to determine location, widely used in travel and transportation." },
    { term: "Theme Park", definition: "An amusement park built around a unifying idea or story, offering rides and entertainment to visitors." },
    { term: "Food and Beverage Service", definition: "The department of a hospitality business responsible for preparing and serving meals and drinks to guests." },
    { term: "Electronic Data Interchange (EDI)", definition: "The computer-to-computer exchange of business documents, such as reservations, in a standard format." },
    { term: "Consumer Confidence Index", definition: "A measure of how optimistic consumers feel about the economy, which influences travel and spending." },
    { term: "Transportation Security Administration (TSA)", definition: "The U.S. federal agency responsible for security screening of travelers at airports." },
    { term: "Executive Housekeeper", definition: "The manager responsible for overseeing a lodging property's cleaning and housekeeping operations." },
    { term: "Front Desk Operations", definition: "The hotel department responsible for guest check-in, check-out, and reservation management." },
    { term: "Housekeeping Department", definition: "The team responsible for cleaning and maintaining guest rooms and public areas at a lodging property." },
    { term: "Banquet Event Order", definition: "A detailed document outlining the specifications for a banquet or catered event, used to coordinate staff." },
    { term: "Convention and Visitors Bureau", definition: "A local organization that promotes a destination to attract tourists, conventions, and meetings." },
    { term: "Familiarization Trip (FAM Trip)", definition: "A complimentary trip offered to travel agents or media to familiarize them with a destination or property." },
    { term: "Itinerary", definition: "A detailed plan or schedule for a trip, including destinations, dates, and activities." },
    { term: "Tourism Multiplier Effect", definition: "The way tourist spending circulates through a local economy, generating additional economic activity." },
    { term: "Ecotourism", definition: "Responsible travel to natural areas that conserves the environment and supports local communities." },
    { term: "All-Inclusive Resort", definition: "A lodging property where the price covers accommodations, meals, drinks, and activities in one package." },
    { term: "Point of Sale (POS) System", definition: "The hardware and software used to process transactions and record sales at a business." },
    { term: "Comp (Complimentary) Room", definition: "A hotel room provided to a guest at no charge, often as a courtesy or promotional gesture." },
    { term: "No-Show", definition: "A guest who has a reservation but fails to arrive or cancel." },
    { term: "Overbooking", definition: "Accepting more reservations than available capacity, anticipating some cancellations or no-shows." },
    { term: "Walk-In Guest", definition: "A guest who arrives at a lodging property seeking a room without a prior reservation." },
    { term: "Rack Rate", definition: "The standard, full price for a hotel room before any discounts are applied." },
    { term: "Property Management System (PMS)", definition: "Software used by a lodging property to manage reservations, check-in/out, billing, and housekeeping." },
    { term: "Central Reservation System", definition: "A network that allows multiple properties or agents to access and book the same inventory of rooms." },
    { term: "Global Distribution System (GDS)", definition: "A computerized network that travel agents and online platforms use to book flights, hotels, and rental cars." },
    { term: "Ground Transportation", definition: "Travel services, such as shuttles or rental cars, that move guests between locations on land." },
    { term: "Tour Package", definition: "A bundled travel product combining transportation, lodging, and activities sold as a single offering." },
    { term: "Culinary Tourism", definition: "Travel motivated by the desire to experience a destination's distinctive food and drink." },
    { term: "Cruise Line", definition: "A company that operates passenger ships offering multi-day voyages combining transportation, lodging, dining, and entertainment." },
    { term: "Cultural Tourism", definition: "Travel motivated by the desire to experience a destination's history, arts, and cultural heritage." },
    { term: "Adventure Tourism", definition: "Travel involving exploration or activities with an element of risk, such as hiking, rafting, or climbing." },
    { term: "Business Travel", definition: "Travel undertaken for work purposes, such as meetings, conferences, or client visits." },
    { term: "Leisure Travel", definition: "Travel undertaken for relaxation, recreation, or personal enjoyment rather than for work." },
    { term: "Group Rate", definition: "A discounted price offered to a party booking a large number of rooms or seats together." },
    { term: "Room Rate", definition: "The price charged for a hotel guest room per night." },
    { term: "Meeting Planner", definition: "A professional responsible for organizing and coordinating conferences, conventions, and corporate meetings." },
    { term: "Site Inspection", definition: "A visit to evaluate a potential venue or property before booking it for an event." },
    { term: "Banquet", definition: "A formal meal or event, typically catered for a large group, often hosted at a hotel or event venue." },
    { term: "Catering", definition: "The business of providing food and beverage service for events, often off-premises or for special occasions." },
    { term: "Hospitality Industry", definition: "The broad category of businesses that provide lodging, food, and related services to travelers and guests." },
    { term: "Tourism Industry", definition: "The businesses and activities involved in serving people traveling away from home for leisure or business." },
    { term: "Guest Satisfaction", definition: "The degree to which a hospitality business meets or exceeds a guest's expectations during their stay or visit." },
    { term: "Service Recovery", definition: "The actions a business takes to resolve a guest's complaint and restore their satisfaction after a service failure." },
    { term: "Upselling", definition: "Encouraging a guest to purchase a higher-priced room, package, or service than originally intended." },
    { term: "Cross-Selling", definition: "Offering a guest complementary products or services in addition to what they originally intended to purchase." },
    { term: "Destination Marketing Organization (DMO)", definition: "An organization, often government-funded, responsible for promoting a specific destination to travelers." },
  ],
  "personal-financial-literacy": [
    { term: "Budget", definition: "A plan for managing income and expenses over a period of time." },
    { term: "Net Worth", definition: "The value of everything a person owns minus everything they owe." },
    { term: "Gross Income", definition: "Total earnings before taxes and other deductions." },
    { term: "Net Income", definition: "Take-home pay remaining after taxes and deductions are subtracted from gross income." },
    { term: "Emergency Fund", definition: "Savings set aside to cover unexpected expenses." },
    { term: "Credit", definition: "The ability to borrow money or access goods and services with the understanding of paying later." },
    { term: "Debt-to-Income Ratio", definition: "A comparison of monthly debt payments to monthly gross income." },
    { term: "Compound Interest", definition: "Interest earned on both the initial deposit and previously earned interest." },
    { term: "Insurance Premium", definition: "The amount paid periodically for an insurance policy." },
    { term: "Tax Deduction", definition: "An expense that can be subtracted from taxable income, lowering the amount of tax owed." },
    { term: "Opportunity Cost", definition: "The value of the next best alternative given up when making a choice." },
    { term: "Identity Theft", definition: "The fraudulent use of someone's personal information, usually for financial gain." },
    { term: "Retirement Account", definition: "A savings account designed to provide income after a person stops working." },
    { term: "Inflation", definition: "The general increase in prices and decrease in purchasing power over time." },
  ],
};
